const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync('travel-english-unit9-reservations.html','utf8'),code=html.match(/<script>([\s\S]*?)<\/script>/)[1];
assert.equal(code.trim(),['day9.js','day9-scenes.js','day9-runtime.js'].map(f=>fs.readFileSync('assets/'+f,'utf8')).join('\n').trim());
assert.equal(html.match(/<style id="day9-styles">([\s\S]*?)<\/style>/)[1].trim(),['day7.css','day9.css'].map(f=>fs.readFileSync('assets/'+f,'utf8')).join('\n').trim());
for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
assert(!/匯出|下載|exportWork|createObjectURL/.test(html));
function boot(saved=[],blocked=false){const els=new Map(),events={},storage=new Map(saved),classes=new Set();const el=s=>{if(!els.has(s))els.set(s,{innerHTML:'',textContent:'',hidden:true,focus(){},setAttribute(){}});return els.get(s);};const ctx=vm.createContext({console,document:{documentElement:{dataset:{}},body:{classList:{toggle:(k,on)=>on?classes.add(k):classes.delete(k),contains:k=>classes.has(k)}},querySelector:el,addEventListener:(n,f)=>events[n]=f},window:{scrollTo(){},addEventListener(){}},localStorage:{getItem:k=>{if(blocked)throw Error('blocked');return storage.get(k);},setItem:(k,v)=>{if(blocked)throw Error('blocked');storage.set(k,v);}},setTimeout:()=>0,clearTimeout(){}});vm.runInContext(code,ctx);return {run:s=>vm.runInContext(s,ctx),el,events,storage,click:(d,id)=>events.click({target:{closest:()=>({dataset:d,id,disabled:false})}}),check:(id,checked)=>events.change({target:{id,checked,dataset:{}}})};}
const {run,el,events,storage,click,check}=boot([['old-lesson','keep']]);
assert.equal(run('labels.length'),7);assert.equal(run('phrases.length'),14);assert.equal(run('clerkReplies.length'),7);
for(let p=0;p<7;p++){run(`navigate(${p})`);assert(el('#main').innerHTML.length>500);assert(!/<details[^>]+ open/.test(el('#main').innerHTML));}
run('navigate(0)');assert(el('#main').innerHTML.indexOf('id="before"')<el('#main').innerHTML.indexOf('class="journey-grid"'));
click({phraseMode:'reply'});for(let i=0;i<7;i++){run('navigate(1)');click({reply:String(i)});assert(el('#main').innerHTML.includes(run(`clerkReplies[${i}].task`)));assert(!/<details[^>]+ open/.test(el('#main').innerHTML));}assert(el('#main').innerHTML.includes('進入互動流程'));
let turns=0;
for(const [sc,slot,decision,pay] of [[0,0,0,0],[0,1,0,0],[1,0,0,0],[1,0,0,1],[1,1,0,0],[1,1,0,1],[1,0,1,0],[1,1,1,0]]){run(`startScene(${sc})`);const n=run('lessons[scene].turns.length');for(let t=0;t<n;t++){
 assert.equal(run('turn'),t);run('choose(0);nextTurn()');assert.equal(run('choice'),-1);check('spoken',true);assert.equal(run('spoken'),false);check('heard',true);check('spoken',true);
 for(let bad=0;bad<run('turnText().options.length');bad++)if(!run(`accepted(turnText(),${bad})`)){run(`choose(${bad});nextTurn()`);assert.equal(run('turn'),t);assert.equal(run('canNext()'),false);assert(el('#main').innerHTML.includes('再試一次'));}
 const set=run('turnText().set'),correct=run('turnText().correct');const c=['slot','entry'].includes(set)?slot:set==='decision'?decision:set==='payment'?pay:correct===null?0:correct;
 run(`choose(${c})`);assert(run('canNext()'));if(t===n-1){const h=el('#main').innerHTML;if(sc===0)assert(h.includes(slot?'19:30':'18:30'));else assert(h.includes(decision?'沒有門票':slot?'14:00':'10:00'));}run('nextTurn()');turns++;
 }assert(run('finished'));}
assert.equal(turns,60);assert.equal(run('state.complete.length'),2);
run('startScene(0)');for(const c of [0,1,0,0,1]){check('heard',true);check('spoken',true);run(`choose(${c});nextTurn()`);}assert(run('turnText().line').includes('six thirty'));run('back();back()');assert.equal(run('booking().slot'),undefined);check('heard',true);check('spoken',true);run('choose(1);nextTurn()');check('heard',true);check('spoken',true);run('choose(1);nextTurn()');assert(run('turnText().line').includes('seven thirty'));check('heard',false);assert(!run('spoken'));assert(!run('canNext()'));
for(const k of run('fields.join(",")').split(','))events.input({target:{dataset:{field:k},value:k+' <img src=x onerror=alert(1)>'}});
run('navigate(5)');assert(!el('#main').innerHTML.includes('<img src=x'));assert(el('#main').innerHTML.includes('&lt;img'));assert(el('#main').innerHTML.includes(run('taskBefore')));
for(let i=0;i<run('skills.length');i++){for(const rating of [0,1,2,0]){click({rating:i+','+rating});assert.equal(run(`state.ratings[skills[${i}].id]`),rating);}}
for(let i=0;i<run('pairActivities.length');i++){run('navigate(4)');click({pair:String(i)});assert.equal((el('#main').innerHTML.match(/data-pair-check=/g)||[]).length,run(`pairActivities[${i}].goals.length`));for(const checked of [true,false,true])events.change({target:{dataset:{pairCheck:i+',0'},checked}});}
run('navigate(6)');click({homeChoice:'0,1'});assert(el('#main').innerHTML.includes('再聽一次'));click({homeChoice:'0,0'});assert(el('#main').innerHTML.includes('答對了'));assert.equal(run('homeCount()'),0);for(const k of run('homeKeys.join(",")').split(','))events.change({target:{dataset:{homeCheck:k},checked:true}});assert.equal(run('homeCount()'),4);
click({},'large');assert.equal(storage.get('travel-lab-text-size'),'large');click({},'large');assert.equal(storage.get('travel-lab-text-size'),'standard');
const restored=boot([...storage]);for(const k of run('fields.join(",")').split(','))assert.equal(restored.run(`state[${JSON.stringify(k)}]`),run(`state[${JSON.stringify(k)}]`));assert.equal(restored.run('homeCount()'),4);assert.equal(restored.run('state.complete.length'),2);assert.equal(restored.run('homeAnswers.join(",")'),'-1,-1');assert.equal(storage.get('old-lesson'),'keep');
const key=run('KEY');assert.equal(boot([[key,'{bad']]).el('#storageNotice').hidden,false);assert.equal(boot([[key,JSON.stringify({ratings:{reserve:99},complete:['bad'],pairChecks:{dinner:null}})]]).run('state.ratings.reserve'),-1);const blocked=boot([],true);blocked.run('state.before="still works";save()');assert.equal(blocked.run('state.before'),'still works');assert.equal(blocked.el('#storageNotice').hidden,false);run('speak("Hello")');assert(el('#toast').textContent.includes('逐字稿'));
// Later lessons may be added concurrently; verify this task's first nine lessons without freezing the catalog size.
const courseFiles=fs.readdirSync('.').filter(f=>/^travel-english(?:-unit[2-9]-[^.]+)?\.html$/.test(f));
for(const file of courseFiles){const text=fs.readFileSync(file,'utf8'),nav=text.match(/<nav class="day-switcher"[\s\S]*?<\/nav>/)[0],links=[...nav.matchAll(/href="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(links).size,links.length,file);for(const required of courseFiles)assert(links.includes(required),file+' missing '+required);assert.equal((nav.match(/aria-current="page"/g)||[]).length,1,file);assert(nav.includes(`href="${file}" aria-current="page"`),file);for(const m of text.matchAll(/href="([^"#]+\.html)"/g))assert(fs.existsSync(m[1]),m[1]);}
assert(!/<script[^>]+src=|<link[^>]+href="(?!data:)|<img[^>]+src="(?!data:)/.test(html));
console.log('PASS Day 09: source/build equality; 7 sections; 8 paths / 60 turns; gates, retry, preferences, dynamic tickets, payment/cancellation, backtracking; independent persistence, ratings, homework, escaping, unavailable storage/audio; 9-way navigation.');
