const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync('travel-english-unit12-how.html','utf8');
const code=html.match(/<script id="day12-app">([\s\S]*?)<\/script>/)[1];
assert.equal(code,['day12.js','day12-scenes.js','day12-runtime.js'].map(f=>fs.readFileSync('assets/'+f,'utf8')).join('\n'));
assert.equal(html.match(/<style id="day12-styles">([\s\S]*?)<\/style>/)[1],fs.readFileSync('assets/day12.css','utf8'));
function boot(saved=[],blocked=false){const storage=new Map(saved),elements=new Map(),events={};const el=s=>{if(!elements.has(s))elements.set(s,{innerHTML:'',textContent:'',hidden:false,open:false,dataset:{},focus(){},setAttribute(){}});return elements.get(s);};const ctx=vm.createContext({console,setTimeout:()=>1,clearTimeout(){},document:{querySelector:el,documentElement:{dataset:{theme:'light',size:'standard'}},addEventListener:(n,f)=>events[n]=f},window:{matchMedia:()=>({matches:false,addEventListener(){}}),addEventListener(){},scrollTo(){}},localStorage:{getItem(k){if(blocked)throw Error('blocked');return storage.get(k)},setItem(k,v){if(blocked)throw Error('blocked');storage.set(k,v)}}});vm.runInContext(code,ctx);return {run:s=>vm.runInContext(s,ctx),el,storage,events,click:dataset=>events.click({target:{closest:()=>({dataset,disabled:false})}}),check:(id,checked)=>events.change({target:{id,checked,dataset:{}}})};}
const b=boot(),{run,el,check,click}=b;
assert.equal(run('course.labels.length'),7);
for(const list of ['phrases','replies','supplements','flows','missions','pairs','quizzes'])assert(run(`new Set(${list}.map(x=>x.id)).size===${list}.length`));
for(let i=0;i<7;i++){run(`navigate(${i})`);assert(el('#main').innerHTML.length>1000);assert(!/<details[^>]* open/.test(el('#main').innerHTML));assert.equal((el('#nav').innerHTML.match(/data-page=/g)||[]).length,7);assert(!/匯出|下載|undefined|NaN|餐巾紙/.test(el('#main').innerHTML));}
run('navigate(0)');assert(el('#main').innerHTML.indexOf('field-before')<el('#main').innerHTML.indexOf('一趟出遊，兩種安排'));assert(el('#main').innerHTML.includes(run('course.task')));run('navigate(5)');assert(el('#main').innerHTML.includes(run('course.task')));
let turns=0;
for(const [f,branch] of [[0,0],[0,1],[1,0],[1,1]]){run(`start(${f})`);const n=run('flows[flow].steps.length');for(let t=0;t<n;t++){
 assert.equal(run('canNext()'),false);run('choose(0);next()');assert.equal(run('choice'),-1);assert.equal(run('turn'),t);check('spoken',true);assert.equal(run('spoken'),false);check('heard',true);check('spoken',true);
 assert(run('currentStep().line.length>3'));assert(run('currentStep().zh.length>3'));
 const size=run('currentStep().objects.length');for(let c=0;c<size;c++)if(!run(`accepted(currentStep(),${c})`)){run(`choose(${c});next()`);assert.equal(run('turn'),t);assert(!run('canNext()'));assert(el('#main').innerHTML.includes('再試一次'));}
 const valid=JSON.parse(run('JSON.stringify(currentStep().valid)')),c=valid.length>1?valid[branch]:valid[0];run(`choose(${c})`);assert(run('canNext()'));run('next()');turns++;
 }assert(run('finished'));if(f===0){assert(run('sceneView().text').includes(branch===0?'博物館':'植物園'));assert(run('currentStep().line').includes(branch===0?'Twenty-four':'Sixteen'));assert(el('#main').innerHTML.includes(branch===0?'24 元':'16 元'));assert.equal((el('#main').innerHTML.match(/class="ticket"/g)||[]).length,2);}else{assert(run('sceneView().text').includes(branch===0?'公園':'咖啡廳'));assert(run('currentStep().line').includes(branch===0?'park':'café'));}}
assert.equal(turns,26);assert.equal(run('state.complete.length'),2);
run('start(0)');check('heard',true);check('spoken',true);run('choose(0);next()');assert(run('currentStep().line').includes('twelve'));run('back()');assert.equal(run('selected("destination")'),undefined);check('heard',true);check('spoken',true);run('choose(1);next()');assert(run('currentStep().line').includes('eight'));run('back()');check('heard',true);check('spoken',true);run('choose(0)');check('heard',false);assert.equal(run('spoken'),false);assert.equal(run('selected("destination")'),undefined);assert(!run('canNext()'));
run('navigate(1)');click({mode:'reply'});for(let i=0;i<run('replies.length');i++){click({reply:String(i)});assert(el('#main').innerHTML.includes(`${i+1} / ${run('replies.length')}`));assert(!/<details[^>]* open/.test(el('#main').innerHTML));}assert(el('#main').innerHTML.includes('進入互動流程'));click({reply:'99'});assert.equal(run('reply'),run('replies.length-1'));
const fields=JSON.parse(run('JSON.stringify(fields)'));for(const key of fields)b.events.input({target:{dataset:{field:key},value:key+' <img src=x onerror=bad()> &'}});
run('navigate(5)');assert(el('#main').innerHTML.includes('&lt;img'));assert(!el('#main').innerHTML.includes('<img'));
for(const id of ['plan','bus','change'])b.events.change({target:{dataset:{pairCheck:id+':1'},checked:true}});
for(const [id,n] of [['connect',1],['route',2],['time',3]])click({rating:id+':'+n});assert.equal((el('#main').innerHTML.match(/class="yellow"/g)||[]).length,3);assert.equal((el('#main').innerHTML.match(/class="green"/g)||[]).length,3);click({rating:'time:1'});assert(!el('#main').innerHTML.includes('class="green"'));
for(const key of ['listen','written','spoken'])b.events.change({target:{dataset:{home:key},checked:true}});
run('navigate(6)');click({quiz:'frequency:2'});assert(el('#main').innerHTML.includes('再聽一次'));click({quiz:'frequency:1'});assert(el('#main').innerHTML.includes('✓ every ten minutes'));
const restored=boot([...b.storage]);for(const key of fields)assert.equal(restored.run(`state.answers[${JSON.stringify(key)}]`),key+' <img src=x onerror=bad()> &');assert.equal(restored.run('state.complete.length'),2);assert.equal(restored.run('Object.values(state.checks).flat().filter(Boolean).length'),3);assert(restored.run('homeProgress()').includes('3 / 3'));
assert(boot([[run('course.id'),'{broken']]).run('storageFailed'));assert(boot([[run('course.id'),'null']]).run('storageFailed'));const blocked=boot([],true);blocked.run('save();speak("hello")');assert(blocked.run('storageFailed'));assert(blocked.el('#toast').textContent.includes('無法朗讀'));
const weird=boot([[run('course.id'),JSON.stringify({answers:{before:7},checks:{plan:[true,'true',1]},ratings:{connect:99},complete:['outing','bad','outing']})]]);assert.equal(weird.run('state.answers.before'),'');assert.equal(weird.run('state.ratings.connect'),0);assert.equal(weird.run('state.complete.length'),1);assert.equal(weird.run('state.checks.plan.filter(Boolean).length'),1);
for(const m of html.matchAll(/href="([^"#]+\.html)"/g))assert(fs.existsSync(m[1]),m[1]);
for(const file of fs.readdirSync('.').filter(f=>/^travel-english.*\.html$/.test(f))){const h=fs.readFileSync(file,'utf8'),nav=h.match(/<nav class="day-switcher"[\s\S]*?<\/nav>/)?.[0];assert(nav,file+' navigation');assert.equal((nav.match(/href="travel-english-unit12-how.html"/g)||[]).length,1,file);assert.equal((nav.match(/aria-current="page"/g)||[]).length,1,file);}
console.log('PASS: generated assets, seven sections, 26 branch steps, retry and gating, state invalidation, short replies, per-task persistence, ratings, text escaping, corrupt/blocked storage, audio fallback and all lesson links.');
